### ISSUE TITLE
Make it Mobile

### ISSUE THREAD

**Issue by friedger** [MonsterEOS/monstereos#12]
Assuming scatter works nicely with Firefox for Android and other mobile browsers, the side should adapt to the device screen size

**Comment by Velua** [comment]
Would absolutely love to see better mobile integration, we'll look further into it when we see Scatter come to mobile.

**Comment by friedger** [comment]
Depends on https://github.com/EOSEssentials/Scatter/issues/106

**Comment by friedger** [comment]
This also affects desktop users

![chat 2018-07-25 09-28-16](https://user-images.githubusercontent.com/1449049/43185792-36786458-8fed-11e8-84cd-3aeeffb28827.png)

**Comment by leordev** [comment]
Not only nice but explore alternatives with IOS Secure enclave maybe. add PKs with battle and pet permissions only. let's explore.
