### ISSUE TITLE
Find a zero margin business model

### ISSUE THREAD

**Issue by friedger** [MonsterEOS/monstereos#13]
Paying for creating a monster seems not a good solution for EOS network.

Users should create value to the other users and reward the other users. 

The development costs of the app should be covered by a percentage on the reward? By working proposal? ..

**Comment by leordev** [comment]
agreed, people are being generous on donations :heart:  that made me remove the creation pet fee... 

I was thinking that when we establish a pet transfer market we could get percentages on transfers... 

did you ever play gunbound? remember the market items? we could create addons like this:

![image](https://user-images.githubusercontent.com/6147142/41556267-3bc9a7ca-7308-11e8-8874-f94b51269e73.png)

looking for a day where we will be using the monsters as profiles pictures, so people could show off their addons :)

**Comment by leordev** [comment]
The development costs of the app should be covered by a percentage on the reward -- that's exactly what we are doing now, percentage on players trading! We want to see players making tons of money, so we can too! 

Closing for now...
