### ISSUE TITLE
JavaScript Code Style

### ISSUE THREAD

**Issue by gaboesquivel** [MonsterEOS/monstereos#145]
Are you ok with adopting StandardJS as default coding style and linter ?

https://standardjs.com

**Comment by leordev** [comment]
Yes, let's go with that but with double quotes instead!

**Comment by leordev** [comment]
I will tackle this with prettier.io

**Comment by gaboesquivel** [comment]
Beware prettier is just code formatting, I think we also want code-quality checks 
https://prettier.io/docs/en/comparison.html

**Comment by leordev** [comment]
yep, nothing changes in our tslint code-quality rules

**Comment by gaboesquivel** [comment]
👍
