### ISSUE TITLE
Add Large seafaring mammal

### ISSUE THREAD

**Issue by Velua** [MonsterEOS/monstereos#31]
We're partnered with LSM as per article https://largeseafaringmammal.com/blogs/news/lsm-x-monstereos-io-large-seafaring-monster-collab

We would like to add LSM to our About page and create a new monster **Wallace the Whale!**

Budget: 2 hours

**Comment by leordev** [comment]
I think as far as about page we are good with this budget, even less! 

But create a new monster is not that simple. We will need to restructure pets table and think about a special monster type, maybe a new table for partners. We were already thinking about that, immortal monsters for important EOS dApps, would be legendary!

**Comment by leordev** [comment]
Goes to #68
