### ISSUE TITLE
Getting a game creator onboard for things like XP, level ups, ranking system and possible animation

### ISSUE THREAD

**Issue by destinysaid** [MonsterEOS/monstereos#33]
This is shaping up to be maybe the biggest or first functional game on any blockchain. While i'm a whole lot skeptical about eos, it would make sense if the speed of the blockchain can be tested in this experiment turned game.

A game developer who knows how to work a functioning XP system(experience points), ranking system, and general game mechanics would help this project move along 100x faster.

**Comment by leordev** [comment]
yeah we need to bring someone with gaming expertise that would love to collaborate (and get paid) to build an effective turn based system, with fair rewards, balance etc

**Comment by leordev** [comment]
this is @rozgo with @MonsterEOS/vertex ! https://vertexstudio.github.io -- we are working in a game design document and a lot of news, and a real game loop is coming! 💪
