### ISSUE TITLE
Support from BPs, Whales and maybe block.one themselve

### ISSUE THREAD

**Issue by destinysaid** [MonsterEOS/monstereos#34]
Support goes into any project that has a vision and a dream, if deals can be made with BPs, or eos whales to fund the project, things will move on nicely. Sure yall can rely on donations, but me being an avid gamer, I see this as something that can go far.

Building a functional game on a blockchain, would be like when spacewar first came out on computers in 1962, you would essentially be building the foundation, and if you guys are good enough, be remembered in history as the first to do this well on a blockchain.

**Comment by leordev** [comment]
thank you very much for your feedback. that's all we want to be: the foundation!

we're very focused in developing everything, all from our ❤️ , but indeed we would be motivated and excited to work on it full time with proper funds! let's wait for proposals.

also we need to check if, as our goal is to be the foundation as code for eos projects, maybe we are qualified for the EOS WPS system. just didn't have time to check it yet. @Velua please help us!!! 😄

**Comment by leordev** [comment]
I think we are keeping up in a good pace now... thanks for @MonsterEOS/vertex team!

We just need to start making money to even get more speed and a lot of improvements, let's see what happens... Closing for now...
