### ISSUE TITLE
Ingame  currency/market place to trade monsters

### ISSUE THREAD

**Issue by destinysaid** [MonsterEOS/monstereos#35]
I get that eosmosters is a little like cryptokitties, but it should be better, a market place where rare and properly evolved monsters can be traded would be awesome.

All monsters can be traded for a currency, it might be a currency created on the eos blockchain or using eos itself.

**Comment by leordev** [comment]
definitely, we are going to think the best strategy here, it's a very delicate theme, not sure if create a token would be better than use EOS itself. (to fund us yes of course, but we need to think about the token purpose)

**Comment by leordev** [comment]
for now, using eos itself
