### ISSUE TITLE
add a monster details page

### ISSUE THREAD

**Issue by leordev** [MonsterEOS/monstereos#43]
shows details of the monster, battle stats and all the care history like fed and bedtime timestamps

also would be interesting to add a personal biography field, so the owner could create stories of the monster

it will help to build value to it

**Comment by friedger** [comment]
Simple page available on
https://friedger.github.io/monstereos-page/#3727
https://github.com/friedger/monstereos-page

**Comment by leordev** [comment]
![image](https://user-images.githubusercontent.com/6147142/44690220-08ed8e00-aa28-11e8-95d9-4ef869ec8424.png)

**Comment by friedger** [comment]
How does it look when logged out?

Leo Ribeiro <notifications@github.com> schrieb am Di., 28. Aug. 2018, 00:36:

**Comment by leordev** [comment]
Same thing. It's a shareable link: 
![image](https://user-images.githubusercontent.com/6147142/44727289-b2279900-aaa7-11e8-9e35-22247f1c968e.png)
