### ISSUE TITLE
Investigate how two feed actions can happen within 5 seconds 

### ISSUE THREAD

**Issue by friedger** [MonsterEOS/monstereos#61]
There were two feed actions reported:

John McCoffee:
106145669  Jul-27-2018, 12:25:34 PM  
feedpet
pet_id: 3347
106145611  Jul-27-2018, 12:25:27 PM  
feedpet
pet_id: 3347

How is that possible?

**Comment by leordev** [comment]
it's fixed already. before we were trying to ignore the feed and update the death time. not needed anymore.
