### ISSUE TITLE
Convert the Frontend to ReactJS, so more people can collaborate

### ISSUE THREAD

**Issue by leordev** [MonsterEOS/monstereos#67]

**Comment by Velua** [comment]
I'm happy to kick this off when I have the room to put it on my plate, do you wanna mimic the existing UI or make some changes? If so feel free to put some stuff in a wireframe, otherwise we'll copy existing.

**Comment by leordev** [comment]
we should probably review the ux indeed. but for now just same ui, I will boilerplate the code with TypeScript and jest as a test framework
