### ISSUE TITLE
Make sure that death_at is set to the correct date once a monster died

### ISSUE THREAD

**Issue by friedger** [MonsterEOS/monstereos#90]
Currently, the monster.death_at field is only updated if the user interacts with the monster after it died.

There should be a mechanism to update that field, or remove that field alltogether.

**Comment by leordev** [comment]
this field is deprecated. I should rename it... for now just ignore this one, we don't use that for anything. the death must be calculated with globalconfig params

**Comment by friedger** [comment]
It is not that easy, as the parameters changed and might change in the
future

Leo Ribeiro <notifications@github.com> schrieb am Mi., 19. Sep. 2018, 20:32:

**Comment by leordev** [comment]
I think the current global config is the valid one. Actually, you would need some kind of chain replay and keep track of global configs history to calculate whenever the parameters were changed... But even like that only the last global config param could be read by the contract and that is what will be applied in case of revive potion being used and if the pet dies again after starving for 72 hours (as now)...

let's not worry about it for now
